from flask import Flask, render_template, request, jsonify
import re

app = Flask(__name__)

# A lightweight educational detector. It does NOT use an external AI API.
# It estimates AI-likeness from writing/code patterns and should not be treated
# as proof that code was generated by AI.

AI_PATTERNS = [
    r"\b(chatgpt|openai|copilot|gemini|claude)\b",
    r"^\s*(here(?:'s| is)|sure[,!]|certainly[,!])",
    r"\b(let me|this code|the following code)\b",
]

def analyze_code(code: str):
    code = code.strip()
    if not code:
        return {
            "score": 0, "label": "No code", "confidence": "Low",
            "signals": ["Please enter some code."]
        }

    lines = [x for x in code.splitlines() if x.strip()]
    comments = [x for x in lines if x.lstrip().startswith(("#", "//", "/*", "*", "<!--"))]
    long_lines = [x for x in lines if len(x) > 120]
    patterns = sum(bool(re.search(p, code, re.I | re.M)) for p in AI_PATTERNS)

    # Heuristic score: intentionally conservative.
    score = 10
    if len(lines) >= 25: score += 8
    if len(lines) >= 60: score += 5
    if len(comments) >= max(3, len(lines)//8): score += 12
    if long_lines: score += min(10, len(long_lines) * 2)
    if patterns: score += min(30, patterns * 10)
    if re.search(r"(TODO|FIXME|generated|auto-generated)", code, re.I): score += 8
    if re.search(r"\b(import|def|class|function|const|let|var|public|private)\b", code): score += 2

    score = min(100, score)

    if score < 30:
        label, confidence = "Likely human-written", "Low"
    elif score < 60:
        label, confidence = "Possibly AI-assisted", "Medium"
    else:
        label, confidence = "Higher AI-like signals", "Medium"

    signals = []
    if patterns: signals.append("AI-related or assistant-style wording detected.")
    if comments: signals.append(f"Found {len(comments)} comment lines.")
    if long_lines: signals.append(f"Found {len(long_lines)} long lines (>120 characters).")
    if len(lines) >= 25: signals.append("The sample contains enough code for a basic heuristic analysis.")
    if not signals: signals.append("No strong heuristic signals were detected.")

    return {"score": score, "label": label, "confidence": confidence, "signals": signals}

@app.route("/")
def index():
    return render_template("index.html")

@app.post("/analyze")
def analyze():
    data = request.get_json(silent=True) or {}
    return jsonify(analyze_code(data.get("code", "")))

if __name__ == "__main__":
    app.run(debug=True, host="127.0.0.1", port=5000)
